### ISSUE TITLE
0.4.1 is missing archives

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/jenkins-version#129]
Hi

0.4.1 was released but only contains source code.

Is it expected ?

We are using renovate to get latest version of jv tool (and many other) and our pipeline detected this issue.

Thanks

**Comment by dduportal** [comment]
Thanks for raising the issue! It's not expected that the archived files are missing. Currently diagnosing why is it missing while the GitHub actions logs are all successfull for this tag 🤔 

Just triggered 0.4.2 to watch the release behavior

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-version/releases/tag/0.4.2 should unblock your renovabot process: can you confirm?

**Comment by jonesbusy** [comment]
Thanks. Yes all good, 0.4.2 works now.

**Comment by dduportal** [comment]
Found the problem : i tried to update the release body while it was being updated by the release process. Which resulted in breaking the release. It was a one time fix so should not happen.

many thanks for raising the issue
